<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductAPI.Domain\ProductAPI.Domain.csproj" />
    <ProjectReference Include="..\ProductAPI.Shared\ProductAPI.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Data\" />
    <Folder Include="Configurations\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
